Remove unused dependencies
OpenTermsArchive/declarations-france pull request #50
Opened 2022-02-08 12:32 UTC by MattiSG

Je n'ai pas l'impression que ces dépendances soient utilisées dans le seul fichier `filters` présent dans ce dépôt 🤔

2022-02-08 13:38 UTC, Ndpnt requested changes
Il manque les changements associés sur le fichier `package-lock.json`

2022-02-09 08:29 UTC, Ndpnt approved these changes

2022-02-09 08:30 UTC, merged

2022-02-09 11:35 UTC, clementbiron commented
@MattiSG c'est fait, peux-tu faire la revue ici https://github.com/OpenTermsArchive/declarations-france/pull/56 ?

2022-02-09 11:36 UTC, Ndpnt commented
J'avais déjà fait…