Fix Instagram
OpenTermsArchive/declarations-france pull request #55
Opened 2022-02-09 11:04 UTC by clementbiron

2022-02-10 11:31 UTC, martinratinaud requested changes
I think it does not work the way you did. :-)

2022-02-10 11:31 UTC, martinratinaud commented on declarations/Instagram.filters.js
> +    if (params.has("h") === true) {
no need for `===true` I guess

2022-02-10 11:31 UTC, martinratinaud commented on declarations/Instagram.filters.js
> +      el.setAttribute("href", params.toString());
here you seem to replace href with only the search params

Best way would maybe to use `new URL(href)`

2022-02-11 08:36 UTC, MattiSG reviewed
Can't wait for Instagram to stop blinking 😊

Congratulations for finding a more stable identifier than the React-generated classes!

2022-02-11 08:36 UTC, MattiSG commented on declarations/Instagram.filters.js
> +export function removeUnessecaryHrefHQueryParam(document) {
```suggestion
export function removeTrackingIDs(document) {
```

2022-02-11 08:36 UTC, MattiSG commented on declarations/Instagram.json
> +      "select": ["div[role=\"main\"]"],
> Do we really need to quote the attribute value?
```suggestion
      "select": ["div[role=main]"],
```
> I'm really not sure about that with pupetteer, please check it if you're interested in the change!

2022-02-15 13:40 UTC, clementbiron commented on declarations/Instagram.json
> +      "select": ["div[role=\"main\"]"],
I just tested it and it works. It's much clearer thanks.

2022-02-15 13:40 UTC, merged